language: scala
cache:
  directories:
    - "$HOME/.ivy2"
    - "$HOME/.cache"
    - "$HOME/.sbt"
jdk:
  - oraclejdk8
before_install:
  - nvm install $NODE_JS_VERSION
  - node --version
  - sudo apt-get install -y awscli
  - npm install --global purescript psc-package
install:
  - git fetch --unshallow
  - npm install && npm run check
  - sbt headerCheck
script:
  - sbt test installerZip writeLanguagePack writeScriptingJavadoc
after_success:
  - aws s3 --region us-east-1 cp Source/Server/equellaserver/target/tle-upgrade*.zip
    s3://edalexdev/equella_artifacts/$TRAVIS_BRANCH/$TRAVIS_BUILD_NUMBER/
  - aws s3 --region us-east-1 cp Installer/target/equella-installer*.zip s3://edalexdev/equella_artifacts/$TRAVIS_BRANCH/$TRAVIS_BUILD_NUMBER/
  - aws s3 --region us-east-1 cp target/reference-language-pack.zip s3://edalexdev/equella_artifacts/$TRAVIS_BRANCH/$TRAVIS_BUILD_NUMBER/
  - aws s3 --region us-east-1 cp target/scriptingapi-javadoc-*.zip s3://edalexdev/equella_artifacts/$TRAVIS_BRANCH/$TRAVIS_BUILD_NUMBER/
  - aws s3 --region us-east-1 rm --recursive s3://edalexdev/equella_artifacts/$TRAVIS_BRANCH/latest/
  - aws s3 --region us-east-1 cp --recursive s3://edalexdev/equella_artifacts/$TRAVIS_BRANCH/$TRAVIS_BUILD_NUMBER/
    s3://edalexdev/equella_artifacts/$TRAVIS_BRANCH/latest/
env:
  global:
    - NODE_JS_VERSION=8.11.3
    - secure: oPNwtBPjC3DT1JykqxjHyX+Asg9fIaHdR27w8TiaogjpILnbYik4MfaUrSxeuhsLGI6gTbFO1xkqo2v6NbNXYGoza74NafLnnn7mYYB6vnebpn1p91liWDo4w5LYFuqY1y7kzNsAcrpfuLwOukLMnx1No5SWToigQR62mapCQ0qgzDyeya5wHspZWS/0PU7bXV3cLNFRDhYW/AdvqUcOJ9R5RQ3l0MZM6OAUkkEn9yrJCcfNYYMQ76T4uCrVvWv6OXygNpVEmUwnN5+Yl10N1hSdbrr7mSHVCiJJSIMqM+yQTjxOylnhao4S5uIfNFyl7yfX43+APDJoGyNmQExAeK5SfjfS+BWhbJKfamqmPzEWu5f9D5wYA8Re8Pqpwqnn92SlHikLCiCWjTS0CUFdAnA2Kq9wF5iJYWNpKSUB0b2C06ewep6sw2UJtLMhXD8BsUb7oAk+h1jVtI5mNPlIeaNORuV69FhcEUbD4bi0IWrmdi4/AjFx/DTDqbpGd4LJgH5AQbQHQBoTkepI151/FdN41a4mdgc4cDUHKr2x8q34BILV3ednUP+We/cTfRQUJphgAd6cTIrAUrE9EaG8g8uI22LCVDH68bNE6LoZqBtVfoy2qos4RTnM4s0/UumHjZaSJPvDOyLlWQ/P4/jN3VYlUaJMcg26ODwXnl3nL4Q=
    - secure: J83GUtzuJL+mxEM429C4qlq4ssURbRMRkpdyqIxrgHA/BU3lnubNjil5hFaOVeCmVE+/F+gQ/5M9j/oyJy9S4Bhs9vVOwkBMMouOYKLSacNkFXMAlz9LtAUInq+6wgmxYXD0NQVCyLLou/JNleUNkmCAgh+a7ZmcyvEfE6datGzf/2M2C4KmntVKn8KiacLUp4kJNbygKnIfqmSbQ5ETLcH55+zUhtviidIVJEjQvBd6kmJUql+I5ATxfW1gA4xLfgVy96aH5XLEpehondv1GPPwEI0Yp1zPURM1BmiIlOxvYN0wrq2D3GyYV/M/Hi+A03MWyTBQPbBZdzh4iIFbqNpASsCv5Sbkkxk+2yMrQdUiDlwvD0GMNDubIqa56C7yg9btdHyeGA5qsmCTl/pdxNNtxhZiiHvq/19LqI+cIZVjEzLFbLqvZ19+qomVCmjxW2OOBXuMBJtV4KfyuZIIj/KyPSK1lB0C8UXfPHJQrJN2OFrbORngpv2uneNHnEUi5ZXrIL2AjzE7AmLlwhChpbB6yeMjuGP9CdRAwNvp9hvQ6uc6gTz/TN43wf5t3UVc7Ax151F6ATKY2EoCcd//vAyzoi9XsDYYD/XUnqbhsZI1Csq9WYOkYao8JiVxSksSC0sQU+9w9L5xYdnhShG6ziETbEczQKaU23pG2KDPk4w=
