version: 0.2

env:
  variables:
    KALTURA_BRANCH: master
    # for this build we still need Oracle JDK for JNLP support
    JAVA_HOME: /opt/oracle-jdk/jdk1.8.0_202
    AUTOTEST_BRANCH: stable-6.6
phases:
  pre_build:
    commands:
      - env
      - yarn global add psc-package-bin-simple@3.0.1
      - export PATH=$JAVA_HOME/bin:$PATH
      - setupBuild
  build:
    commands:
      - sbt -Dconfig.file=${HOME}/build.conf -Dsbt.log.noformat=true test installerZip writeLanguagePack
  post_build:
    commands:
      - publishBuild
      - echo "Finished"
cache:
  paths:
    - '/root/.ivy2/**/*'
    - '/root/.npm/**/*'
    - '/root/.sbt/**/*'
    
